src/baseline_bots/bots/__init__.py, src/baseline_bots/bots/dipnet/RealPolitik.py, src/baseline_bots/bots/dipnet/no_press_bot.py, src/baseline_bots/bots/smart_order_accepter_bot.py, src/baseline_bots/utils.py
fixes #21 . This also reformatted some files I did not work on when I ran the formatter.
=> Moved get_state_value to utils

src/baseline_bots/bots/dipnet/RealPolitik.py, src/baseline_bots/bots/dipnet/dipnet_bot.py, src/baseline_bots/bots/smart_order_accepter_bot.py, src/baseline_bots/utils.py, tests/bot_tests/bots_test.py
I have updated utils / dipnet/ realpolitik
=> best order for proposals to utils

.github/workflows/CI.yml, Dockerfile
Added pytests to test files in /test/
=> CI for testing baseline bots

src/baseline_bots/bots/random_stance_bot.py, src/baseline_bots/bots/random_support_proposer_bot.py
=> feat: removed references of BotReturnData and fixed code accordingly

src/baseline_bots/bots/smart_order_accepter_bot.py
=> SOA proposal reply

src/baseline_bots/bots/smart_order_accepter_bot.py, src/baseline_bots/utils.py, tests/bot_tests/SOA_test.py
=> fix game instance

src/baseline_bots/bots/smart_order_accepter_bot.py
=> Soa get stance

containers/allan_dip_bot/Dockerfile, requirements.txt, src/baseline_bots/bots/smart_order_accepter_bot.py, src/baseline_bots/parsing_utils.py, tests/bot_tests/SOA_test.py, tests/bot_tests/gameplay_framework.py
as Denis raised
```
Traceback (most recent call last):
File "/model/src/model_server/baseline_bots/run_bot.py", line 197, in <module>
asyncio.run(launch(hostname=host, port=port, game_id=game_id,power_name=power, bot_type=bot_type, outdir=outdir))
File "/data/env3.7/lib/python3.7/asyncio/runners.py", line 43, in run
return loop.run_until_complete(main)
File "/data/env3.7/lib/python3.7/asyncio/base_events.py", line 573, in run_until_complete
return future.result()
File "/model/src/model_server/baseline_bots/run_bot.py", line 80, in launch
await play(hostname, port, game_id, power_name, bot_type, outdir)
File "/model/src/model_server/baseline_bots/run_bot.py", line 139, in play
ret_data = await bot(rcvd_messages)
File "/data/env3.7/lib/python3.7/site-packages/tornado/gen.py", line 782, in …
```
=> Fix gen proposal reply

src/baseline_bots/bots/smart_order_accepter_bot.py
avoid sending message during non-movement phases and consider proposals
=> fix SOA to send messages/consider proposal only in m phase

src/baseline_bots/bots/smart_order_accepter_bot.py
=> Remove randomization

src/baseline_bots/bots/smart_order_accepter_bot.py
update logic to see powers as ally if stance>= ally_threshold in global msg
=> global msg update

src/baseline_bots/bots/smart_order_accepter_bot.py
instead of having `self.stance.stance[power][power] > 0` everywhere in SOA, we change to store
```
self.allies
self.foes
self.neutral
```
This reflects in every function related to the stance vector
=> consistent ally-neutral-enemy

src/baseline_bots/bots/dipnet/transparent_bot.py, src/baseline_bots/bots/random_proposer_bot.py, src/baseline_bots/bots/smart_order_accepter_bot.py, src/baseline_bots/parsing_utils.py, src/baseline_bots/randomize_order.py, src/baseline_bots/utils.py, tests/randomize_order_test.py
This pull shouldn't change randomization back to the way it "should" be, which is slightly different, but it fixes a minor bug in the current randomization code and changes the tests to fit the version we currently have. Also makes formatting changes to a handful of other files. Fixes #128
=> Fix randomize order test

src/baseline_bots/bots/smart_order_accepter_bot.py
add filter to aggressive through convoy orders!
=> add filter agg convoy

.github/workflows/CI.yml, Dockerfile, tests/bot_tests/SOA_test.py, tests/bot_tests/simple_SOA_test.py
This PR adds the dockerized CI pipeline, which support diplomacy research.
Please note that almost all tests for SOA_Bot functionality have been incorrectly written. They should look like the following:
```python
class TestSOABot(AsyncTestCase):
@testing.gen_test
def test_play(self):
```
See `simple_SOA_test` for more implementation details.
Main SOA_bot test is still problematic: #136 
Resolves #129 (test failing)
Resolves #130  (test failing)
Resolves #132 (figured out that this is the case)
=> Dockerized CI pipeline with diplomacy research support

.github/workflows/CI.yml, Dockerfile, containers/allan_dip_bot/Dockerfile, requirements.txt, src/baseline_bots/bots/random_proposer_bot.py, src/baseline_bots/bots/smart_order_accepter_bot.py, tests/bot_tests/SOA_test.py, tests/bot_tests/gameplay_framework_async.py, tests/bot_tests/simple_SOA_test.py
Resolves #141 
Resolves #136 
Resolves #101 
Resolves #138
=> added coroutine test wrapper

.gitmodules
submodule of cicero in baseline_bots
=> module for cicero

src/baseline_bots/bots/smart_order_accepter_bot.py
- Added PRP() to the ALY VSS message
- Change countries in ALY VSS to daide-compliant format (e.g., ALY (ENGLAND ITALY)... -> ALY (ENG ITA))
=> daide message fix

containers/allan_dip_bot/run_bot.py, src/baseline_bots/bots/smart_order_accepter_bot.py
Added aggressiveness factor that can be A (aggressive), M (moderate), or F (friendly).
=> Included parameters in SOA bot to set hyperparameters

.gitmodules, .pre-commit-config.yaml, Makefile, requirements.txt
We discussed in the student meeting that the submodule should be removed. In addition, we discussed in the general meeting how we need to use the proper `diplomacy` branch. Along with this, I did some cleanup of the requirements.
=> Remove submodule and improve requirements

.gitignore, containers/allan_dip_bot/BUILD.md, scripts/create_game.py, scripts/run_games.sh, tests/bot_tests/SOA_test.py
I created a script to make running games on both locally and on TACC much easier. It can only run one type of agent with one configuration, but it should make general testing much easier.
I included two other commits that contain some relevant changes.
=> Add script to run games more easily

containers/allan_dip_bot/run_bot.py, src/baseline_bots/bots/smart_order_accepter_bot.py
Added optional arguments to adjust hyperparameters when running the SOA bot via run_bot.py (used by Singularity /Docker to run bots).
=> Add optional commandline hyperparameter arguments

src/baseline_bots/bots/smart_order_accepter_bot.py, tests/bot_tests/SOA_test.py, tests/bot_tests/simple_SOA_test.py
I made some code changes while trying to debug the communication issue. They should be upstreamed sooner rather than later.
=> Improve `SmartOrderAccepterBot` code

requirements.txt, src/baseline_bots/bots/smart_order_accepter_bot.py
import new stance module;
stance logging via game log
=> logging of stance changes + end game stance flip

containers/allan_dip_bot/run_bot.py, src/baseline_bots/bots/smart_order_accepter_bot.py, src/baseline_bots/parsing_utils.py, src/baseline_bots/utils.py
This PR implements the simple messaging loop and contains some related changes, including a fix to a messaging bug I had noticed while reading through the code.
The only "regression" I noticed was that our testing time increased from ~40s to ~140s on my local machine. This is almost entirely accounted for by the messaging logic needing to be run an extra two times.
=> Add message loop to SOA bot

containers/allan_dip_bot/run_bot.py, scripts/create_game.py, scripts/download_game.py, scripts/run_games.sh
This PR contains some improvements to my `run_game.sh` script, including a change suggested by @DenisPeskov in <https://github.com/ALLAN-DIP/baseline_bots/pull/165#discussion_r1115075758>.
=> Improve `run_games.sh`

requirements.txt, src/baseline_bots/bots/smart_order_accepter_bot.py, src/baseline_bots/parsing_utils.py, src/baseline_bots/utils.py, tests/bot_tests/SOA_test.py, tests/utils_test.py
- include new stance modules (default betrayal flip/ cleaned stance log / force update stance)
- support PCE parsing and response
- REJ ALY/PCE from powers with stance scores below the threshold
-  update stance and allies after replying to ALY/PCE
=> Improve Alliance and Peace Logic

src/baseline_bots/bots/smart_order_accepter_bot.py
I added a large amount of intent logging.
=> Add more intent logging

requirements.txt, src/baseline_bots/bots/smart_order_accepter_bot.py, src/baseline_bots/utils.py, tests/utils_test.py
identify potential invalid messages with daidepp
=> Check the syntax of outgoing messages

requirements.txt, src/baseline_bots/bots/baseline_bot.py, src/baseline_bots/bots/dipnet/dipnet_bot.py, src/baseline_bots/bots/dipnet/no_press_bot.py, src/baseline_bots/bots/dipnet/pushoverdipnet.py, src/baseline_bots/bots/dipnet/selectively_transparent_bot.py, src/baseline_bots/bots/dipnet/transparent_bot.py, src/baseline_bots/bots/random_proposer_bot.py, src/baseline_bots/bots/smart_order_accepter_bot.py, src/baseline_bots/parsing_utils.py, src/baseline_bots/randomize_order.py, src/baseline_bots/utils.py, tests/bot_tests/SOA_test.py, tests/bot_tests/bots_test.py, tests/bot_tests/gameplay_framework.py, tests/utils_test.py
I'm not done cleaning up the branch for the `daidepp` conversion yet, but I figured it would be good to release batches of commits to make the branch easier to work with. This is the first batch that uses `daidepp` for more than just DAIDE validation.
I have tested this thoroughly with our test suite, run ~5 years of a game, and did a close read of the code. I expect that this caught most bugs I introduced, but some might have still slipped through.
=> Convert logic to use `daidepp` (part 1)

.pre-commit-config.yaml, containers/allan_dip_bot/run_bot.py, src/baseline_bots/__init__.py, src/baseline_bots/bots/smart_order_accepter_bot.py, src/baseline_bots/randomize_order.py, src/baseline_bots/utils.py, tests/bot_tests/SOA_test.py, tests/utils_test.py
Now that we have some more time, I'm taking care of some technical debt. This PR adds flake8 to carry out some simple precommit checks. It revealed some bugs during this process.
=> Add flake8 to precommit checks
